### ISSUE TITLE
msgtype m.notice is not a valid type. results in no pushnotification sent

### ISSUE THREAD

**Issue by ACiDGRiM** [jooola/zabbix-matrix-webhook#33]
the msgtype m.notice is silently accepted by the matrix server, however it's not listed in the API as one of the valid msgtypes

https://www.matrix.org/docs/guides/client-server-api#sending-messages

changing msgtype to m.text allows pushnotifications to be sent

By the way, with this small fix, being able to use matrix for push notifications is the greatest upgrade to my monitoring situation. Thank you.

**Comment by jooola** [comment]
Hmm, I followed the specs, and choose to pick `m.notice` because of what a notice should be used for:

https://spec.matrix.org/v1.5/client-server-api/#mnotice

So maybe this is a server implementation bug, or the specs are lacking some details about those push notifications.

I am no matrix expert, so we should probably raise the question in the spec repo or synapse repo.

I am unsure if there is any benefit from making this msgtype configurable by the user.

**Comment by jooola** [comment]
In the spec `Firstly, clients should present m.notice messages to users in a distinct manner,` might be the reason why the server implementation didn't send a push notification, but that is somewhat difficult to guess.

**Comment by jooola** [comment]
It seems that the predefined rules disable push notification for notices by default: https://spec.matrix.org/v1.5/client-server-api/#predefined-rules

So maybe this should be configurable by the users ?

I am happy to change the msgtype to `m.text` again but I need to find some official docs to make sure I am not making a mistake by doing so.

**Comment by ACiDGRiM** [comment]
I think you're correct to use m.notice after reviewing the doc. I recently found that the client setting for bot notifications is related. The default is no push for bots, but it's disappointing that the setting is global for notification or noisy. Meaning either all room bots pop a notification or none.

I did open a bug with the element chat project
